use Mix.Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with brunch.io to recompile .js and .css sources.
config :five9s, Five9sWeb.Endpoint,
  http: [port: 4444],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  secret_key_base: :crypto.strong_rand_bytes(200) |> Base.url_encode64 |> binary_part(0, 200),
  watchers: [node: ["node_modules/brunch/bin/brunch", "watch", "--stdin",
                    cd: Path.expand("../assets", __DIR__)]]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# command from your terminal:
#
#     openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" -keyout priv/server.key -out priv/server.pem
#
# The `http:` config above can be replaced with:
#
#     https: [port: 4000, keyfile: "priv/server.key", certfile: "priv/server.pem"],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

config :five9s,
       configs: :s3, # :yml, :s3
       s3_bucket: System.get_env("S3_BUCKET"), # required if configs == :s3
       admin_key: "admin",
       admin_verifier: "verified"

# Watch static and templates for browser reloading.
config :five9s, Five9sWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r{priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$},
      ~r{priv/gettext/.*(po)$},
      ~r{lib/five9s_web/views/.*(ex)$},
      ~r{lib/five9s_web/templates/.*(eex)$}
    ]
  ]

log_level = System.get_env("LOG_LEVEL") || "info"
# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n",
                level: String.to_atom(log_level)

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20
